language: elixir
elixir:
  - "1.9"
otp_release:
  - "22.0"

jobs:
  include:
    - stage: test
      env:
        - MIX_ENV=test
      script: make check
    - env:
        - MIX_ENV=dialyzer
      script: mix dialyzer

stages:
  - install.rebar
  - install.hex
  - install.deps
  - test

env:
  - DIALYZER_PLT_FILE=priv/plts/dialyzer.plt

cache:
  directories:
    - priv/plts
